version: '3.9'
services:
  frontend:
    image: northgatefrontend-frontend:latest
    volumes:
      - /home/docker_volumes/frontend:/app
      - /app/node_modules
      - /home/docker_volumes/certs/server.crt:/app/cert/server.crt
      - /home/docker_volumes/certs/server.key:/app/cert/server.key
    ports:
      - "3001:3000"
    networks:
      - web
networks:
  web:
    driver: overlay