version: '3.9'
services:
  frontend:
    image: ng_frontend:latest
    environment:
      - WDS_SOCKET_PORT=443
    volumes:
      - /opt/frontend/src:/app/src
      - /opt/frontend/public:/app/public
      # Старайтесь избегать анонимных томов
      # Они плодятся а потом теряются с командой
      # docker volume prune
      - modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - northgatevologda
volumes:
  modules:
networks:
  northgatevologda:
    external: true
