version: '3.9'
services:
  frontend:
    image: northgatefrontend-frontend:latest
    environment:
      - WDS_SOCKET_PORT=443
    volumes:
      - /home/docker_volumes/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - northgatevologda
networks:
  northgatevologda:
    external: true
