version: '3.9'
services:
  backend_alpha:
    image: ng_backend:latest
    env_file:
      - global.env
      - backend.env
    volumes:
      - /opt/repos/NorthGateBackend_alpha/api:/backend/api
      - /opt/repos/NorthGateBackend_alpha/config:/backend/config
      - /opt/repos/NorthGateBackend_alpha/manage.py:/backend/manage.py
    ports:
      - "8000:8000"
    hostname: backend_alpha
    networks:
      - northgatevologda
    environment:
      - BACKEND_SECRET_KEY=/run/secrets/BACKEND_SECRET_KEY
      - BACKEND_DB_NAME=/run/secrets/BACKEND_DB_NAME
      - BACKEND_DB_USER=/run/secrets/BACKEND_DB_USER
      - BACKEND_DB_PASSWORD=/run/secrets/BACKEND_DB_PASSWORD
      - BACKEND_DB_HOST=/run/secrets/BACKEND_DB_HOST
      - BACKEND_DB_PORT=/run/secrets/BACKEND_DB_PORT
      - BACKEND_ENVIRONMENT=/run/secrets/BACKEND_ENVIRONMENT
      - YANDEX_KEY=/run/secrets/YANDEX_KEY
      - YANDEX_URL=/run/secrets/YANDEX_URL
    secrets:
      - BACKEND_SECRET_KEY
      - BACKEND_DB_NAME
      - BACKEND_DB_USER
      - BACKEND_DB_PASSWORD
      - BACKEND_DB_HOST
      - BACKEND_DB_PORT
      - BACKEND_ENVIRONMENT
      - YANDEX_KEY
      - YANDEX_URL
networks:
  northgatevologda:
    external: true
secrets:
  BACKEND_SECRET_KEY:
    external: true
  BACKEND_DB_NAME:
    external: true
  BACKEND_DB_USER:
    external: true
  BACKEND_DB_PASSWORD:
    external: true
  BACKEND_DB_HOST:
    external: true
  BACKEND_DB_PORT:
    external: true
  BACKEND_ENVIRONMENT:
    external: true
  YANDEX_KEY:
    external: true
  YANDEX_URL:
    external: true
