version: '3.9'
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8181:8181"
    environment:
      - NIFI_WEB_HTTP_PORT=8181
    volumes:
      - /home/docker_volumes/nifi:/opt/nifi/nifi-current/ls-target
    networks:
      - northgatevologda
networks:
  northgatevologda:
    external: true

