version: '3.9'
services:
  nginx:
    image: ng_nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- /home/docker_volumes/certbot/conf:/etc/letsencrypt
      #- /home/docker_volumes/certbot/www:/var/www/certbot
      #- /home/docker_volumes/static:/var/www/static
      #- /home/docker_volumes/media:/var/www/media
      - config:/etc/nginx/conf.d/
    networks:
      - northgatevologda
  #certbot:
  #  image: certbot/certbot:latest
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #  volumes:
  #    - /home/docker_volumes/certbot/conf:/etc/letsencrypt
  #    - /home/docker_volumes/certbot/www:/var/www/certbot
  #  networks:
  #    - northgatevologda
volumes:
  config:
networks:
  northgatevologda:
    external: true
