version: '3.9'
services:
  postgres:
# Старайтесь всегда виксировать версию!
# Через месяц в latest могут внести такие изменения, коорые погубят всё
# приложение и мы можем потратить очень много времени на поиск причины
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB_FILE=/run/secrets/DATABASE_DB_NAME
      - POSTGRES_USER_FILE=/run/secrets/DATABASE_DB_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/DATABASE_DB_PASSWORD
    secrets:
      - DATABASE_DB_NAME
      - DATABASE_DB_USER
      - DATABASE_DB_PASSWORD
    volumes:
      - /home/docker_volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - northgatevologda
  pgadmin:
# Старайтесь всегда виксировать версию!
# Через месяц в latest могут внести такие изменения, коорые погубят всё
# приложение и мы можем потратить очень много времени на поиск причины
    image: dpage/pgadmin4:7.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=northgate@mail.ru
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/DATABASE_PGADMIN_PASSWORD
    secrets:
      - DATABASE_PGADMIN_PASSWORD
    volumes:
      - /home/docker_volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - northgatevologda
    depends_on:
      - postgres
networks:
  northgatevologda:
    external: true
secrets:
  DATABASE_DB_NAME:
    external: true
  DATABASE_DB_USER:
    external: true
  DATABASE_DB_PASSWORD:
    external: true
  DATABASE_PGADMIN_EMAIL:
    external: true
  DATABASE_PGADMIN_PASSWORD:
    external: true
