version: '3.9'
services:
  postgres:
    image: postgis/postgis:latest
    restart: always
    environment:
      - POSTGRES_DB_FILE=/run/secrets/DATABASE_DB_NAME
      - POSTGRES_USER_FILE=/run/secrets/DATABASE_DB_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/DATABASE_DB_PASSWORD
    secrets:
      - DATABASE_DB_NAME
      - DATABASE_DB_USER
      - DATABASE_DB_PASSWORD
    volumes:
      - /home/docker_volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - northgatevologda
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=northgate@mail.ru
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/DATABASE_PGADMIN_PASSWORD
      - PGADMIN_ENABLE_TLS=True
    secrets:
      - DATABASE_PGADMIN_PASSWORD
    volumes:
      - /home/docker_volumes/pgadmin:/var/lib/pgadmin
      - /home/docker_volumes/certs/server.crt:/certs/server.cert
      - /home/docker_volumes/certs/server.key:/certs/server.key
    ports:
      - "5050:443"
    networks:
      - northgatevologda
    depends_on:
      - postgres
networks:
  northgatevologda:
    external: true
secrets:
  DATABASE_DB_NAME:
    external: true
  DATABASE_DB_USER:
    external: true
  DATABASE_DB_PASSWORD:
    external: true
  DATABASE_PGADMIN_EMAIL:
    external: true
  DATABASE_PGADMIN_PASSWORD:
    external: true